Feature/android digital pass
javaBin/jz-native-mobile-apps pull request #14
Opened 2019-08-19 20:31 UTC by nicolactic

Har ikke fått til å nuke databasen. Den sjekker jo bare variabelen opp mot seg selv når man inkrementerer nummeret?

2019-08-20 05:44 UTC, kkho commented
> Har ikke fått til å nuke databasen. Den sjekker jo bare variabelen opp mot seg selv når man inkrementerer nummeret?

Bra jobba!
Du kan bytte db navn istedenfor for nå. Da det vil rette seg mot det. det finner du typ :

https://github.com/javaBin/jz-native-mobile-apps/blob/develop/JZAndroid/app/src/main/java/no/schedule/javazone/v3/provider/ScheduleDatabase.java#L28

Endre på dette og da vil den lage en ny db fil og bruke den. dette blir en "midlertidig" fix .

Sjekk dette for å slette db:
https://stackoverflow.com/questions/4406067/how-to-delete-sqlite-database-from-android-programmatically

2019-08-27 10:47 UTC, kkho commented on JZAndroid/app/src/main/java/no/schedule/javazone/v3/provider/ScheduleDatabase.java
> +    //if (version != CUR_DATABASE_VERSION) {
Dropper dere hver gang appen kjøres?
Det burde det vel ikke :)

2019-09-03 14:45 UTC, Sardtok requested changes

2019-09-03 14:45 UTC, Sardtok commented on JZAndroid/app/build.gradle
> -    testImplementation 'junit:junit:4.12'
Dere må ikke ta bort JUnit fra enhetstestene. Den er nødvendig både for enhetstester, og for UI-tester. Ellers kan dere eventuelt fjerne eksempeltesten siden det uansett ikke er noen reelle enhetstester.

2019-09-05 08:22 UTC, Sardtok commented
Jeg merger denne, så legger jeg inn igjen JUnit etterpå. Det begynner å bli litt viktig å få ut disse endringene.

2019-09-05 08:22 UTC, merged